upstream website_upstream {
    server website:8080;
}

upstream registry_upstream {
    server fictional-registry:8080;
}

upstream media_owner_upstream {
    server sample-media-owner:8080;
}

server {
    listen 80;
    listen [::]:80;
    server_name oohdi.org www.oohdi.org;
    return 301 https://$host$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name example-media-owner.oohdi.org;
    return 301 https://$host$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name example-registry.oohdi.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name oohdi.org www.oohdi.org;

    ssl_certificate /etc/nginx/certs/oohdi.crt;
    ssl_certificate_key /etc/nginx/certs/oohdi.key;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    location / {
        proxy_pass http://website_upstream;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name example-media-owner.oohdi.org;

    ssl_certificate /etc/nginx/certs/oohdi.crt;
    ssl_certificate_key /etc/nginx/certs/oohdi.key;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    location / {
        proxy_pass http://media_owner_upstream;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name example-registry.oohdi.org;

    ssl_certificate /etc/nginx/certs/oohdi.crt;
    ssl_certificate_key /etc/nginx/certs/oohdi.key;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    location / {
        proxy_pass http://registry_upstream;
    }
}
